-- IMPORTAÇÃO DE CLIENTES DA PLANILHA
BEGIN;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('AERO CHAVE', 'pj', 'SEM-CNPJ-0001', '17988414140', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('ARTS CHAVEIRO', 'pj', 'SEM-CNPJ-0002', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('BRUNO GOIÂNIA', 'pj', 'SEM-CNPJ-0003', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CENTER CHAVES', 'pj', 'SEM-CNPJ-0004', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAV3IRO JEFERSON', 'pj', 'SEM-CNPJ-0005', '17 99132-4656', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO 13 DE MAIO', 'pj', 'SEM-CNPJ-0006', '(16) 3627-6826', NULL, '[{"street":"AV. TREZE DE MAIO","number":"777","complement":null,"neighborhood":"JARDIM PAULISTANO","city":"RIBEIRÃO PRETO","state":"SP","zip_code":"14090-270","is_default":true}]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ABC', 'pj', 'SEM-CNPJ-0007', '61996140483', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ADEMAR', 'pj', 'SEM-CNPJ-0008', '16993078867', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ADRIANO', 'pj', 'SEM-CNPJ-0009', '61991338722', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ASAS', 'pj', 'SEM-CNPJ-0010', '61984748000', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ASAS SUL', 'pj', 'SEM-CNPJ-0011', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO BOM JESUS', 'pj', 'SEM-CNPJ-0012', '17981160455', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO CAMPEÃO CONSTRUÇÃO', 'pj', 'SEM-CNPJ-0013', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO CANAA', 'pj', 'SEM-CNPJ-0014', '17992647541', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO CASA NOVA', 'pj', 'SEM-CNPJ-0015', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO COIMBRA', 'pj', 'SEM-CNPJ-0016', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO DR DAS CHAVES', 'pj', 'SEM-CNPJ-0017', '1699398-3707', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO E CARIMBOS MAIAMI', 'pj', 'SEM-CNPJ-0018', '(16) 3636-6185', NULL, '[{"street":"AV. DO CAFÉ","number":"348","complement":null,"neighborhood":"VILA TIBERIO","city":"RIBEIRÃO PRETO","state":"SP","zip_code":"14050-220","is_default":true}]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO E CIA', 'pj', 'SEM-CNPJ-0019', '17981944295', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ELLOS', 'pj', 'SEM-CNPJ-0020', '61991246561', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO ESTORIL', 'pj', 'SEM-CNPJ-0021', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO EXPRESS', 'pj', 'SEM-CNPJ-0022', '61984067000', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO FIO DE OURO', 'pj', 'SEM-CNPJ-0023', '61983510044', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO FLASH', 'pj', 'SEM-CNPJ-0024', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO FLASH 2', 'pj', 'SEM-CNPJ-0025', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO FOGUINHO', 'pj', 'SEM-CNPJ-0026', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO G', 'pj', 'SEM-CNPJ-0027', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO JADEL', 'pj', 'SEM-CNPJ-0028', '16993901937', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO JAPONES', 'pj', 'SEM-CNPJ-0029', '1698117-6600', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO JEFERSON', 'pj', 'SEM-CNPJ-0030', '16994196467', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO JP', 'pj', 'SEM-CNPJ-0031', '17988201505', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO LIDER', 'pj', 'SEM-CNPJ-0032', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO MAIAMI', 'pj', 'SEM-CNPJ-0033', '16992453913', NULL, '[{"street":"EM MAOS","number":"1","complement":null,"neighborhood":"","city":"RIBEIRÃO PRETO","state":"SP","zip_code":"38400454","is_default":true}]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO MARIO', 'pj', 'SEM-CNPJ-0034', NULL, NULL, '[{"street":"R. JOÃO MOBÍGLIA","number":"","complement":null,"neighborhood":"JARDIM MANOEL PENNA","city":"RIBEIRÃO PRETO","state":"SP","zip_code":"14098-300","is_default":true}]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO PARAGUAI', 'pj', 'SEM-CNPJ-0035', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO PONTO IDEAL', 'pj', 'SEM-CNPJ-0036', '61991267204', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO RELOJ ADRIANO', 'pj', 'SEM-CNPJ-0037', '6199343538', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO REQUINTE', 'pj', 'SEM-CNPJ-0038', '16988300003', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO RESOLV', 'pj', 'SEM-CNPJ-0039', '1698166-8781', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO SÃO DEOCLECIANO', 'pj', 'SEM-CNPJ-0040', '179992278254', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO TECNOCHAVE', 'pj', 'SEM-CNPJ-0041', '61991581318', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO TONIN', 'pj', 'SEM-CNPJ-0042', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('CHAVEIRO XINXA', 'pj', 'SEM-CNPJ-0043', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('DAVI CHAVEIRO', 'pj', 'SEM-CNPJ-0044', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('DENYS', 'pj', 'SEM-CNPJ-0045', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('DURAN & SPAGNOL CHAVEIRO 24HORAS', 'pj', 'SEM-CNPJ-0046', '(16) 99961-4557', NULL, '[{"street":"R. AURORA","number":"1043","complement":null,"neighborhood":"VILA TIBERIO","city":"RIBEIRÃO PRETO","state":"SP","zip_code":"14050-100","is_default":true}]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('DURAN SPAGNOL', 'pj', 'SEM-CNPJ-0047', '1699961-4557', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('ELDER CHAVEIRO', 'pj', 'SEM-CNPJ-0048', '61974006924', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('ENIGMA', 'pj', 'SEM-CNPJ-0049', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('FRANK CHAVEIRO', 'pj', 'SEM-CNPJ-0050', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('JAFFAS', 'pj', 'SEM-CNPJ-0051', '61984901457', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('JR CHAVEIRO', 'pj', 'SEM-CNPJ-0052', '17-99123-5061', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('LB CHAVES', 'pj', 'SEM-CNPJ-0053', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('LUNAR SOM', 'pj', 'SEM-CNPJ-0054', NULL, NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('MAGAIVER', 'pj', 'SEM-CNPJ-0055', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('MARCÃO CHAVE', 'pj', 'SEM-CNPJ-0056', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('MARIO CHAVEIRO', 'pj', 'SEM-CNPJ-0057', '17991422550', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('OPÇÃO CHAVEIRO', 'pj', 'SEM-CNPJ-0058', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('RAFA SOUND', 'pj', 'SEM-CNPJ-0059', '16981170557', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('SOM MAIS', 'pj', 'SEM-CNPJ-0060', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('SOS CHAVES', 'pj', 'SEM-CNPJ-0061', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('TAGUÁ CHAVES', 'pj', 'SEM-CNPJ-0062', '61974008512', NULL, '[]') ON CONFLICT (document) DO NOTHING;
INSERT INTO public.clients (name, type, document, phone, email, addresses) VALUES ('TESTE', 'pj', 'SEM-CNPJ-0063', '34998651112', NULL, '[]') ON CONFLICT (document) DO NOTHING;
COMMIT;